name: Stevensphotography
favicon: null
layout_spectrum: 0.24624
typography_spectrum: 0.62521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdf0'
    - '#e4cec1'
    - '#ae766a'
    - '#151132'
    - '#2e3466'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.9590787873603404
  rhythmicContrast: 1
purpose: []
