name: Stevensphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#151515'
    - '#e9c2b1'
    - '#94867d'
    - '#4f4138'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
