name: Steven Pederson Photography
favicon: null
layout_spectrum: 0.25626
typography_spectrum: 0.76044
title: Steven Pederson Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#151515'
    - '#e9c2b1'
    - '#94867d'
    - '#4f4138'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
